name: Cucumber Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Show current directory
        run: pwd

      - name: List files in root directory
        run: ls -la

      - name: List files in QA directory
        run: ls -la QA

      - name: List files in cucumber-java directory
        run: ls -la QA/cucumber-java

      - name: Run Maven tests
        run: mvn test
        working-directory: ./QA/cucumber-java
