name: Run Cypress tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:12.17.1  # immagine ufficiale Cypress con tutto dentro
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Run Cypress tests
        run: npx cypress run
